FROM openjdk:17.0.1-jdk
COPY ApplicationControllers/ApplicationREST/target/ApplicationREST-1.0-SNAPSHOT.jar ApplicationREST-1.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","ApplicationREST-1.0-SNAPSHOT.jar"]